class Prefectur< ActiveHash:: Base
  self.data = [
    { id: 1, prefectur: '---'},
    { id: 2, prefectur: '北海道' },
    { id: 3, prefectur: '青森県' },
    { id: 4, prefectur: '岩手県' },
    { id: 5, prefectur: '宮城県' },
    { id: 6, prefectur: '秋田県' },
    { id: 7, prefectur: '山形県' },
    { id: 8, prefectur: '福島県' },
    { id: 9, prefectur: '茨城県' },
    { id: 10, prefectur: '栃木県' },
    { id: 11, prefectur: '群馬県' },
    { id: 12, prefectur: '埼玉県' },
    { id: 13, prefectur: '千葉県' },
    { id: 14, prefectur: '東京都' },
    { id: 15, prefectur: '神奈川県' },
    { id: 16, prefectur: '新潟県' },
    { id: 17, prefectur: '富山県' },
    { id: 18, prefectur: '石川県' },
    { id: 19, prefectur: '福井県' },
    { id: 20, prefectur: '山梨県' },
    { id: 21, prefectur: '長野県' },
    { id: 22, prefectur: '岐阜県' },
    { id: 23, prefectur: '静岡県' },
    { id: 24, prefectur: '愛知県' },
    { id: 25, prefectur: '三重県' },
    { id: 26, prefectur: '滋賀県' },
    { id: 27, prefectur: '京都府' },
    { id: 28, prefectur: '大阪府' },
    { id: 29, prefectur: '兵庫県' },
    { id: 30, prefectur: '奈良県' },
    { id: 31, prefectur: '和歌山県' },
    { id: 32, prefectur: '鳥取県' },
    { id: 33, prefectur: '島根県' },
    { id: 34, prefectur: '岡山県' },
    { id: 35, prefectur: '広島県' },
    { id: 36, prefectur: '山口県' },
    { id: 37, prefectur: '徳島県' },
    { id: 38, prefectur: '香川県' },
    { id: 39, prefectur: '愛媛県' },
    { id: 40, prefectur: '高知県' },
    { id: 41, prefectur: '福岡県' },
    { id: 42, prefectur: '佐賀県' },
    { id: 43, prefectur: '長崎県' },
    { id: 44, prefectur: '熊本県' },
    { id: 45, prefectur: '大分県' },
    { id: 46, prefectur: '宮崎県' },
    { id: 47, prefectur: '鹿児島県' },
    { id: 48, prefectur: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :items
end
